dist: trusty
sudo: required
language: bash
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2019-02/run.sh |
  bash
notifications:
  slack:
    rooms:
      secure: DTMKXyKrniBzWnaA5h0fPZRyXMf7j/6YSsZhRwsiN93Y53deYFZyak1W+MM9wa0bBNZVRpXRvAmV4iP2OL8jXaVLLpoerUzpKup4oKtMnWvGYyLUTc2s0gRvA2x0uWq7prBFyJ6UKL+hLrQZVU0RH4JB3MCyU+9+BiR4IHcw5iqG84u8qzVdn53u63rNPTZD3q8csGkQmK0PsH/DnEWJnT3FBsEsOGIlaxEY1I3AWzXb3QGAtdXl39l/JugRnijy9vvD1gA5lJT/uwpryzwP84BBLF5ScN9sT1xhhV2fYswpe0qsHR+d6t/iy5jCHbNqP3Toph/ktGrIF3RzRNgueJrYIS5SfQaGrNvfplPHPX+ZWWWQ69wtT+A35+brJsSzi1ExkCrNMDfokyu1AQl7LoGzl0zyHvPnHXmuV1X9I1MmWIBOrPkrvb5DkiPu0EW5aUltjr2U6/FiqfL6pCs+zEp3Fbx13uBAc86L1i98i5hnMnP7ePaL4t+Hj+9bMpkoRQV2CGPnyVIbQ4o6gwYhxpopl9fwKYCu6I0rWNKKOhvIOZXuDOCiJHI03Oo2JAil5kk8G8QPza31l6fIAjHRLRD+Mjq9rZ6g68S1GdMQP0CWsrlWONb3DMPpsbpA/WxUi8lQlAjd0C5yvkZVFWecRcxrSigHyQ2ujjsFr7op/QA=
