---
- name: Install docker and deploy docker-compose
  hosts: logging
  become: true
  tasks:
  - name: add docker GPG key
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

  - name: add docker apt repo
    apt_repository:
      repo: deb https://download.docker.com/linux/ubuntu bionic stable
      state: present

  - name: install docker
    apt:
      update_cache: yes
      state: latest
      name:
      - docker-ce
      - docker-ce-cli
      - containerd.io

  - name: install python dependencies
    apt:
      update_cache: yes
      state: latest
      name: python3-pip

  - name: install 'Docker SDK for Python'
    pip:
      name:
       - docker
       - docker-compose

  - name: create a directory
    ansible.builtin.file:
      path: "/srv/logging/conf"
      state: directory
      mode: 0755

  - name: Copy file with owner and permissions
    ansible.builtin.copy:
      src: "../../docker/{{item}}"
      dest: /srv/logging/
    loop:
      - docker-compose.yml
      - docker-compose-logging.yml

  - name: Copy configuration file
    ansible.builtin.copy:
      src: ../fluentd/fluent.conf
      dest: /srv/logging/conf

  - name: deploy docker-compose for logging
    community.docker.docker_compose:
      project_src: /srv/logging/
      files:
        - docker-compose-logging.yml

  - name: Check if port 24224 is listening
    wait_for:
      port: 24224
      delay: 10
      timeout: 180
      msg: "Timeout waiting for 24224 to respond"
    register: port_check
    ignore_errors: yes

  - name: deploy docker-compose with services
    community.docker.docker_compose:
      project_src: /srv/logging/
      files:
        - docker-compose.yml



