global:
  slack_api_url: 'https://hooks.slack.com/services/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'

route:
  receiver: 'slack-notifications'

receivers:
  - name: 'slack-notifications'
    slack_configs:
      - channel: '#allerts'