version: '3.3'
services:
  post_db:
    image: mongo:3.2
    volumes:
      - post_db:/data/db
    networks:
      - back_net

  comment_db:
    image: mongo:3.2
    volumes:
      - comment_db:/data/db
    networks:
      - back_net

  ui:
    image: danilkuch/ui
    environment:
      - POST_SERVICE_HOST=post
      - POST_SERVICE_PORT=5000
      - COMMENT_SERVICE_HOST=comment
      - COMMENT_SERVICE_PORT=9292
      - ZIPKIN_ENABLED=true
    ports:
      - "9292:9292"
    depends_on:
      - post
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: service.ui
    networks:
      - front_net

  post:
    image: danilkuch/post
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: service.post
    environment:
      - ZIPKIN_ENABLED=true
    depends_on:
      - post_db
    ports:
      - "5000:5000"
    networks:
      - back_net
      - front_net

  comment:
    image: danilkuch/comment
    depends_on:
      - comment_db
    environment:
      - ZIPKIN_ENABLED=true
    networks:
      - front_net
      - back_net

volumes:
  post_db:
  comment_db:

networks:
  front_net:
  back_net:
